config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "static_pages#home"

  resources :messages, only: [:new, :create]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end
  
  match 'users/conversations', to: 'users#user_conversations', as: 'user_conversations', via: 'get'

  resources :users

  
  

end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id                     :integer          not null, primary key
#  sender_id              :integer
#  recipient_id           :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#

class Conversation < ActiveRecord::Base
  has_many :messages
  belongs_to :user
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                     :integer          not null, primary key
#  body                   :text
#  conversation_id        :integer
#  user_id                :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#

class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :text
#  last_name              :text
#  about                  :text
#  birthday               :date
#  latitude               :integer
#  longitude              :integer
#  occupation             :text
#  field                  :text
#  orientation            :text
#  interest               :text
#  physical               :text
#  free_time              :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  image_file_name        :string
#  image_content_type     :string
#  image_file_size        :integer
#  image_updated_at       :datetime
#  gender                 :string
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_attached_file :image, :styles => { :small => "250x250>", :medium => "400x400>", :thumb => "50x50>" }, :default_url => "/images/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50}
	validates :email, presence: true

	acts_as_messageable
	
  has_many :conversations, :foreign_key => :sender_id

  def mailboxer_email(object)
	  email
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception
  before_action :authenticate_user!,:except => [:home]  

 #  rescue_from ActiveRecord::RecordNotFound do
	# flash[:warning] = 'Resource not found.'
	# redirect_back_or root_path
	# end
	 
	# def redirect_back_or(path)
	#   redirect_to request.referer || path
	# end

  	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :first_name, :last_name, :about, :occupation, :field, :orientation, :interest, :physical, :free_time, :image, :gender, :birthday)}
	end
  
  def after_sign_in_path_for(user)
  	users_path
  end

  def after_sign_up_path_for(user)
  	user_url(user)
  end



end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]

  def index
    @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def reply
    #mailbox method reply_to_conversation helps a lot. it will take a conversation to reply to
    #and message body
    current_user.reply_to_conversation(@conversation, params[:body])
    # {body: {content: "" }}
    # {body: {content: "", user_id: 3 }}
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
  
private
  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
end

#have to permit

app/controllers/messages_controller.rb
  class MessagesController < ApplicationController
    #before_action :authenticate_user!
 
  def new
  end
 
  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Your message has been sent!"
    #pass the recipients, body of message and subject of message
    redirect_to conversation_path(conversation)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # def user_conversations
  #   @conversations = current_user.mailbox.conversations.paginate :page => params[:page], :per_page => 50
  # end 

  # # GET /users/1
  # # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
      # raise "Not current user" if @user.id != current_user.id || !user_signed_in?
    end

    # Never trust parameters from te scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :about, :gender, :image, :birthday, :occupation, :field, :orientation, :interest, :physical, :free_time, :area)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def recipients_options
    s = ''
	    User.all.each do |user|
	      s << "<option value='#{user.id}'>#{user.first_name}</option>"
	    end
	    s.html_safe
	  end
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.number_field :recipient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/_participants.html.erb
<table>
		<tr>
			<% conversation.participants.each do |participant| %>
			  <% unless participant == current_user %>
				  	<td><%= image_tag participant.image(:thumb) %></td>
				</span>
			  <% end %>
			<% end %>
		</tr>
</table>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Conversations</h1>
<%= link_to 'Start conversation', new_message_path, class: 'btn btn-primary', :style => "color: white", :id => "blueBG" %>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Subject</th>
			<th>Latest Message</th>
			<th>Last Updated</th>
			<th>Participant</th>
		</tr>
	</thead>
	<tbody>
		<% @conversations.each do |c| %>
		  <tr data-link="<%= conversation_path(c) %>" style="cursor: pointer">
				<td><%= c.subject %></td>
				<td><%= c.last_message.body %></td>
				<td><%= time_ago_in_words(c.last_message.created_at)%> ago</td>
			    <td><%= render 'conversations/participants', conversation: c %></td>
			</tr>
		<% end %>
	</tbody>

</table>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<h2>Your chat:</h2>
<br>
<h4>Participants:</h4>
  <strong><%= render 'conversations/participants', conversation: @conversation %></strong>
</h4>
 
<div class="panel panel-default">
  <div class="panel-heading"><strong><%= @conversation.subject %></strong></div>
  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <% message = receipt.message %>
          <div class="media">
            <div class="media-right">
              <%= image_tag message.sender.image(:thumb) %>
              <p class="media-heading"><%= message.sender.first_name %></p>
            </div>
   
            <div class="media-body">
              <div class="comment">
                <p><%= message.body %></p>
              </div>
              <small>(<%= time_ago_in_words(message.created_at)%> ago)</small>
            </div> 
          </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: "btn btn-success pull-right", :id =>"blueBG" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="blueBG">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to (image_tag "FirstSightLogo.png"), root_path, :class => "btn btn-primary" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <% if user_signed_in? %>
        <%= link_to "FirstSight ", users_path, :class => "btn btn-primary btn-lg mdi-action-question-answer", :id =>"blueBG" %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Discover", users_path %></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to 'My Messages', conversations_path %></li>
            <li><%= link_to "#{current_user.first_name}, Logout", destroy_user_session_path, :method => :delete  %></li>
          </ul>
        <% else %>
        <%= link_to "FirstSight ", root_path, :class => "btn btn-primary btn-lg mdi-action-question-answer pull-left", :id =>"blueBG" %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Signup", new_user_registration_path %></li>
          </ul>
        <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://bootsnipp.com/dist/bootsnipp.min.css?ver=70eabcd8097cd299e1ba8efe436992b7">
    <link rel="icon" href="../../favicon.ico">
    
    <style>
    #masonry-container {
    background: #FFF;
    padding: 5px;
    margin-bottom: 20px;
    border-radius: 5px;
    clear: both;
    -webkit-border-radius: 5px;
       -moz-border-radius: 5px;
            border-radius: 5px;
    }
  </style>
  <script>
    $(function(){
      $('#masonry-container').masonry({
        itemSelector: '.box',
        columnWidth: 100,
        gutterWidth: 40,
        itemSelector: '.box',
        columnWidth: 100,
        isAnimated: !Modernizr.csstransitions,
        isRTL: true
      });

    });
  </script>
    <title>FirstSight</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>

    <%= csrf_meta_tags %>

    <%= yield :js_html %>

    <script>
        <%= yield :js %>
    </script>

  </head>

  <body style="background:white">
    <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="container alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <div class="container transitions-enabled" id="masonry-rails" style="background:white">
        <br>
  	    <%= yield %>
      </div>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <p><strong>Subject</strong></p>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', :style => "text-align:center" %>
  </div>
 
  <div class="form-group">
    <p><strong>Message</strong></p>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true, :style => "text-align:center" %>
  </div>
 
  <div class="form-group">
    <p><strong>Recipient</strong></p>
    <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control', :style => "text-align:center" %>
  </div>
 
  <%= submit_tag 'Send', class: "btn btn-default pull-right", :id =>"blueBG", :style => "color: white" %>
<% end %>

app/views/messages/new.html.erb
<div class="container">
	<div class="col-md-8" style="float: none; margin: 0 auto">
		<h1>New Message</h1>

		<%= render 'form' %>
		
		<%= link_to 'Back', user_conversations_path, class: "btn btn-default", :id =>"blueBG", :style => "color: white" %>
	</div>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/static_pages/home.html.erb
<div id="slider1_container" style="position: relative; margin: 0 auto;
  top: 0px; left: 0px; width: 1300px; height: 500px; overflow: hidden;" align="center">
  <!-- Loading Screen -->
  <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
      <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;
          top: 0px; left: 0px; width: 100%; height: 100%;">
      </div>
      <div style="position: absolute; display: block; background: <%= image_url "loading.gif" %> no-repeat center center;
          top: 0px; left: 0px; width: 100%; height: 100%;">
      </div>
  </div>
    <!-- Slides Container -->
  <div data-u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1000px;
    height: 500px; overflow: hidden;", align="center">
    <div>
        <img data-u="image" src="<%= image_url "slideshowimg2.jpg" %>" alt="" />
        <div style="position: absolute; width: 480px; height: 120px; top: 300px; left: 30px; padding: 5px;
            text-align: left; line-height: 36px; font-size: 24px;
                color: #FFFFFF;">
               "If it wasn't for FirstSight, I don't think I would've made it to the White House" <br>- Michelle Obama
        </div>
      </div>
      <div>
        <img data-u="image" src="<%= image_url "slideshowimg4.jpg" %>" alt="" />
        <div style="position: absolute; width: 350px; height: 120px; top: 300px; left: 30px; padding: 5px;
            text-align: left; line-height: 36px; font-size: 26px;
                color: #FFFFFF;">
                "I scored girls just like I scored goals on FirstSight" <br>- David Beckham
        </div>
      </div>
      <div>
          <img data-u="image" src="<%= image_url "slideshowimg3.jpg" %>" alt="" />
          <div style="position: absolute; width: 480px; height: 120px; top: 300px; left: 450px; padding: 5px;
              text-align: right; line-height: 36px; font-size: 23px;
                  color: black;">
                  "Without Kim Kardashian, would I still be the most hated family? Thanks, FirstSight." <br>- Kanye West
          </div>
      </div>
      <div>
        <img data-u="image" src="<%= image_url "LoveBirds.jpg" %>" alt="" />
        <div style="position: absolute; width: 380px; height: 120px; top: 100px; left: 615px; padding: 5px;
            text-align: right; line-height: 36px; font-size: 24px;
                color: white;">
                "If you were expecting Prince Charming, I'm sorry. He's taken." <br>- Phillip Sumetphong
        </div>
      </div>
    </div>
  </div>
<div align="center">
	<h1>Where dreams come true</h1>
	<hr>
	<p>FirstSight is Thailand's first ever dating website THAT WORKS. Through FirstSight, you can discover tons of people in Bangkok and even chat with them directly! We cut out all the unnecessary bits that's standing between you and your soulmate.</p>

	<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary", :id =>"blueBG" %>
  
</div>

app/views/users/index.html.erb
<script>
 jQuery(function(){
   var $container = $('#container');
   $container.imagesLoaded( function () {
       itemSelector: '.box',
       animate: true
   });
  });
</script>
<h1> Matches Found:</h1>
<h4 style="text-transform: none;">In this page, you can look through all the users on FirstSight. You can also filter your search by Gender and Area of Interest. Search away!</h4>
<div id="filters" align="center">
  <div class="ui-group">
    <h3 style="text-transform: none">Fitler by Gender</h3>
    <br>
    <div class="button-group js-radio-button-group" data-filter-group="gender">
      <button class="button is-checked" data-filter="">Any Gender</button>
      <button class="button" data-filter=".Male">Male</button>
      <button class="button" data-filter=".Female">Female</button>
    </div>
  </div>

  <div class="ui-group">
    <h3 style="text-transform: none">Filter by Area of Interest (Work or Education)</h3>
    <br>
    <div class="button-group js-radio-button-group" data-filter-group="field">
      <button class="button is-checked" data-filter="">Any</button>
      <button class="button" data-filter=".Sciences">Sciences</button>
      <button class="button" data-filter=".MathematicsPhysics">Math/Physics</button>
      <button class="button" data-filter=".ComputerScienceTechnology">Computer/Technology</button>
      <button class="button" data-filter=".ArtsFashionMusicMedia">Arts</button>
      <button class="button" data-filter=".Other">Other</button>
    </div>
  </div>
</div>
<hr>
<div class="isotope">
  <% @users.each do |user| %>
    <% if current_user.id != user.id %>
      <div class="col3 color-shape <%= user.field %> <%= user.gender %>" align="center">
        <%= image_tag user.image.url(:medium), class: "img-profile" %>
        <h3><strong><%= user.first_name %> <%= user.last_name %></strong></h1>
        <h4 style="text-transform: none"><%= user.gender %>, <%= Date.today.year - user.birthday.to_date.year%> years old</h4>
        <h3><%= link_to "Find out more", user_path(user.id), class: "btn btn-success", :id =>"blueBG" %></h3>
      </div>
    <% end %>
  <% end %>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('img').load(function(){
            $(".content_photo").masonry();
        });
        $(".content_photo").masonry();
    });
</script>

app/views/users/show.html.erb
<div class="container text-center">
  <div>
    <% if current_user.id != @user.id %>
      <button class="btn btn-fab btn-raised btn-success" ONCLICK="window.location.href='<%= new_message_path %>'"><i class="mdi-image-edit"></i></button> 
    <% end %>   
      <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      <br>
      <%= image_tag @user.image.url(:medium) %>
      <h3 style="text-transform: none"><strong>About:</strong> <%= @user.about %></h3>
      <% if current_user.id == @user.id %>
        <h5><%= link_to 'Edit', edit_user_path(id: current_user.id), class: "btn btn-default", :id =>"blueBG", :style => "color: white"%></h5>
      <% end %>
  </div>
  <br>
    <table class="table" align="center" style="width:500px">
      <tbody>
        <tr>
          <td><h4 align="left"><strong>Gender:</strong></td></h4>
          <td><%= @user.gender %></td>
        </tr>
        <tr>
          <td><h4 align="left"><strong>Birthday:</strong></td></h4>
          <td><%= @user.birthday %><td>
        </tr>
         <tr>
          <td><h4 align="left" ><strong>Interested In:</strong></td></h4>
          <td><%= @user.interest %><td>
        </tr>
        <tr>
          <td><h4 align="left"><strong>Occupation:</strong></td></h4>
          <td><%= @user.occupation %><td>
        </tr>
        <tr>
          <td><h4 align="left"><strong>Area of Interest:</strong></td></h4>
          <td><%= @user.field %><td>
        </tr>
        <tr>
          <td><h4 align="left"><strong>Physical Attributes:</strong></td></h4>
          <td><%= @user.physical %><td>
        </tr>
        <tr>
          <td><h4 align="left"><strong>What I do in my free time:</strong></td></h4>
          <td><%= @user.free_time %><td>
        </tr>
      </tbody>
    </table>
    <% if current_user.id != @user.id %>
      <button class="btn btn-success" ONCLICK="window.location.href='<%= new_message_path %>'" style="color: white">Send Message</button> 
    <% end %>   
    <br>

  <%= link_to 'Back', users_path , class: "btn btn-default", :id =>"blueBG", :style => "color: white"%>
    
</div>
      <br>
          </div>              
        </div>              
      </div>            
    </div>
</div>